version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-2:026090537156:task-definition/product-service-task"
        LoadBalancerInfo:
          ContainerName: "product-container"
          ContainerPort: 8080