# buildspec.yml
version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: 026090537156
    AWS_DEFAULT_REGION: ap-northeast-2
    IMAGE_REPO_NAME: anysinsa/product
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Running tests...
      - chmod +x ./gradlew
      - ./gradlew test --info
      - echo Building the Gradle project...
      - ./gradlew build -x test
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"product-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo Updating ECS task definition...
      - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition product-service-task --query 'taskDefinition' --output json)
      - NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy) | .containerDefinitions[0].image = "'$REPOSITORY_URI:$IMAGE_TAG'"')
      - NEW_TASK_INFO=$(aws ecs register-task-definition --family product-service-task --cli-input-json "$NEW_TASK_DEFINITION")
      - NEW_REVISION=$(echo $NEW_TASK_INFO | jq '.taskDefinition.revision')
      - echo New task definition revision is $NEW_REVISION
      - echo Updating appspec.yml with new task definition...
      - sed -i.bak -e "s|product-service-task|product-service-task:$NEW_REVISION|g" appspec.yml
      - echo New task definition revision is $NEW_REVISION
      - echo Updating appspec.yml with new task definition...
      - TASK_DEFINITION_ARN=$(echo $NEW_TASK_INFO | jq -r '.taskDefinition.taskDefinitionArn')
      - sed -i.bak -e "s|<TASK_DEFINITION>|$TASK_DEFINITION_ARN|g" appspec.yml

reports:
  junit:
    files:
      - 'build/test-results/test/*.xml'
    file-format: "JUNITXML"
    discard-paths: false

cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'

artifacts:
  files:
    - appspec.yml
    - imagedefinitions.json
    - build/test-results/test/*.xml
    - build/reports/tests/test/**/*