server:
  port: 8080  # 공통 포트 설정

spring:
  application:
    name: product
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: product.cluster-ct0gsiiwy4xd.ap-northeast-2.rds.amazonaws.com:3306/product
    username: admin
    password: qudtjf12?!
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true