server:
  port: 8080  # 공통 포트 설정
  tomcat:
#    max-threads: 500
#    max-connections: 20000
#    accept-count: 1000
##    connection-timeout: 30000  # 30초
    max-threads: 300          # 500 -> 300 (태스크당 부하 고려)
    max-connections: 10000    # 20000 -> 10000
    accept-count: 500         # 1000 -> 500
    connection-timeout: 5000  # 명시적으로 5초 설정
management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  otlp:
    tracing:
      endpoint: http://localhost:4317
      protocol: grpc
otel:
  service:
    name: ${spring.application.name}
  exporter:
    otlp:
      endpoint: http://localhost:4317
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
spring:
  application:
    name: product
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver
    url: jdbc:otel:mysql://product.cluster-ct0gsiiwy4xd.ap-northeast-2.rds.amazonaws.com:3306/product
#    url: jdbc:otel:mysql:replication://product.cluster-ct0gsiiwy4xd.ap-northeast-2.rds.amazonaws.com:3306,product.cluster-ro-ct0gsiiwy4xd.ap-northeast-2.rds.amazonaws.com:3306/product
    username: admin
    password: qudtjf12?!
    hikari:
#      maximum-pool-size: 100
#      minimum-idle: 10
#      connection-timeout: 30000
#      idle-timeout: 600000
#      max-lifetime: 1800000
      maximum-pool-size: 75    # 100 -> 75 (스레드 수 대비)
      minimum-idle: 20         # 10 -> 20 (초기 부하 대비)
      connection-timeout: 5000 # 30000 -> 5000
      idle-timeout: 300000     # 600000 -> 300000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
#spring:
#  application:
#    name: product
#  h2:
#    console:
#      enabled: true
#  datasource:
#    driver-class-name: io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver
#    url: jdbc:otel:mysql:replication://localhost:3306,localhost:3307,localhost:3308/test
#    username: test
#    password: test
#    hikari:
#      maximum-pool-size: 100
#      minimum-idle: 10
#      connection-timeout: 30000
#      idle-timeout: 600000
#      max-lifetime: 1800000
#  jpa:
#    defer-datasource-initialization: true
#    open-in-view: false
#    properties:
#      hibernate:
#        format_sql: false