spring:
  application:
    name: musinsa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://my-aurora.cluster-ct0gsiiwy4xd.ap-northeast-2.rds.amazonaws.com:3306/mydatabase
    username: admin
    password: qudtjf12?!
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true